companalysis/companalysis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("twitter/", include("twitter.urls", namespace="twitter")),

]

companalysis/twitter/urls.py
from django.urls import path
from . import views

app_name = 'twitter'

urlpatterns = [
    path("", views.index, name="index"),
    path("scroller", views.scroller, name="scroller"),
    path("feeds", views.feeds, name="feeds"),
]

companalysis/twitter/models.py
from django.db import models

# Create your models here.

companalysis/twitter/views.py
from datetime import timedelta, datetime
from django.shortcuts import render
import math
import configparser
import psycopg2
from sys import exit
from functools import lru_cache

config = configparser.ConfigParser()
config.read('../conf.ini')

pghost = config['Postgres']['host']
pguser = config['Postgres']['user']
pgpass = config['Postgres']['password']
pgdb = config['Postgres']['db']
tweetaccounts = config['Twitter']['accounts']
tzoffset = int(config['Timezone']['tzoffset'])
interval = config['Postgres']['interval']

# Create your views here.
def index(request):
    context = dict()
    return render(request, "twitter/index.html", context=context)

def scroller(request):
    #if request.method == "GET":
    # pull tweets for the last 5 minutes and pass them to template
    data = list()
    refresh = int(int(interval) / 2 * 60)
    try:
        conn = psycopg2.connect(f"dbname={pgdb} user={pguser} password={pgpass} host={pghost}")
    except Exception as e:
        print(e)
        exit("Unable to connect to postgres database!")
    cur = conn.cursor()
    cur.execute(
        f"SELECT accname, hashtags, symbols, ttext, created from twitter where created >= CURRENT_TIMESTAMP AT TIME ZONE 'UTC' - INTERVAL '{interval} minutes' ORDER BY created DESC;")
    tweets = cur.fetchall()
    for tweet in tweets:
        local = tweet[4] + timedelta(hours=tzoffset)
        twDict = {"account": tweet[0], "hashtags": tweet[1], "symbols": tweet[2], "ttext": tweet[3], "created": local}
        data.append(twDict)
    # 12 tweets displayed / minute
    # expand the dictionary to accomodate this
    runMins = round(int(interval) / 2)
    tweetsNeeded = runMins * 12

    # 4 tweets fit on a page, if less than this, don't duplicate tweets, if not duplicate
    #print("Initial length: ", len(data))
    if len(data) > 4:
        dataLength = len(data)
        multiplier = round(tweetsNeeded / dataLength)
        data = data * multiplier
    #print("With multplier: ", len(data))
    return render(request, "twitter/scroller.html", {'refresh': refresh, 'interval': interval, "data": data})

#@lru_cache(maxsize=2)
def feeds(request):
    """Display a list of feeds from the config file with additional information"""
    # also pull additional information on them from db and display it
    # get info from config file
    data = dict()
    # {barrons: {name: barrons, id: barrons, description: <description>, url: <url>, followers: <num followers>}}
    tweetList0 = tweetaccounts.splitlines()
    tweetList = [item for item in tweetList0 if item]
    try:
        conn = psycopg2.connect(f"dbname={pgdb} user={pguser} password={pgpass} host={pghost}")
    except Exception as e:
        print(e)
        exit("Unable to connect to postgres database!")
    cur = conn.cursor()
    # select distinct on (acctid), tjson from twitter where acctid in {list from conf.ini}
    cur.execute(f"SELECT DISTINCT ON (acctid) acctid, tjson from twitter where acctid in {tuple(tweetList)};")
    accounts = cur.fetchall()
    for item in accounts:
        acctName = item[0]
        acctDict = {"username": item[1]["user"]["name"], "screenname": item[1]["user"]["screen_name"],
                    "description": item[1]["user"]["description"], "url": item[1]["user"]["url"],
                    "followers": item[1]["user"]["followers_count"], "totaltweets": item[1]["user"]["statuses_count"]}
        data.update({acctName: acctDict})

    return render(request, "twitter/feeds.html", {'data': data})

companalysis/twitter/templates/twitter/base.html
<!DOCTYPE html>
{% load static %}
{% block extra_head %}{% endblock %}
<html>
<head>
    <title>{% block title %}FinTwit{% endblock %}</title>
    <link href="{%  static 'css/twitter.css'  %}" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark sticky-top bg-dark">
        <a class="navbar-brand" href="{% url 'twitter:index' %}">#Twitter Finance</a>
        <button aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
                data-target="#navbarCollapse" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'twitter:scroller' %}">Twitter Scroller</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'twitter:feeds' %}">Twitter Feeds</a>
                </li>
            </ul>

        </div>
    </nav>
    <div id = "content">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

companalysis/twitter/templates/twitter/feeds.html
{% extends "twitter/base.html" %}
{% block content %}
<div class="container">
    <table class="table table-striped table-bordered table-hover">
        <tr>
            <td></td>
            <td></td>
        </tr>
        {% for key, value in data.items %}

        <tr>
            <td>User name</td>
            <td><a href={{ value.url }}>{{ value.username.strip }}</a></td>
        </tr>
        <tr>
            <td>Screen name</td>
            <td>{{ value.screenname.strip }}</td>
        </tr>
        <tr>
            <td>Description</td>
            <td>{{ value.description.strip }}</td>
        </tr>
        <tr>
            <td>Followers</td>
            <td>{{ value.followers }}</td>
        </tr>
        <tr>
            <td>Total Tweets</td>
            <td>{{ value.totaltweets }}</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
        </tr>

        {% endfor %}
    </table>
</div>
{% endblock %}

companalysis/twitter/templates/twitter/index.html
{% extends "twitter/base.html" %}

companalysis/twitter/templates/twitter/scroller.html
{% extends "twitter/base.html" %}
{% block extra_head %}

<meta http-equiv="refresh" content="{{ refresh }}"/>
{% endblock %}
{% block content %}

<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script>
    function getScrollbarWidth() {
  let $div = $('<div />').css({
      width: 100,
      height: 100,
      overflow: 'auto',
      position: 'absolute',
      top: -1000,
      left: -1000
  }).prependTo('body').append('<div />').find('div').css({
      width: '100%',
      height: 200
  });
  let scrollbarWidth = 100 - $div.width();
  $div.parent().remove();
  return scrollbarWidth;
}
// not working to get these values...  scroller won't scroll back up.  workaround implemented
let userInteract = false;
let scrollHeight = $('#scrollbox').prop('scrollTop');
let scrollboxHeight = $('#scrollbox').height();
let heightDiff = scrollHeight - scrollboxHeight + getScrollbarWidth();
let delta = 1;

let laststop = $('#scrollbox').scrollTop();
setInterval(
function() {
    if (!userInteract) {
      let scrollTop = $('#scrollbox').scrollTop();
      laststop = scrollTop;
      $('#info').text(scrollTop + ' ' + scrollHeight);
      if (scrollTop >= heightDiff) {
          delta = -1;
      } else if (scrollTop <= 0) {
          delta = 1;
      }
      $('#scrollbox').scrollTop(scrollTop + delta);
      let scrolltopdelta = scrollTop + delta;
  }
}, 50);
</script>
{% if not data %}
        <h1> No tweets in the last {{ interval }} minutes!</h1>
{% endif %}

<div id="scrollbox">
    {% for item in data %}
    <div id="tscroll"><h1>{{ item.ttext }}</h1>
            <p> {{ item.created }}, {{ item.account }} </p>
            {% if item.hashtags or item.symbols %}
                <p>{{ item.hashtags }}, {{ item.symbols }}</p>
            {% endif %}
        </div>
  <hr />
    {% endfor %}

</div>

    {% endblock %}